'use client';

import React, { memo, useState } from 'react';
import { HelpCircle, Shield, Zap, TrendingUp, AlertTriangle, X } from 'lucide-react';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';

interface RiskExplainerProps {
  type: 'PT' | 'YT' | 'SPLIT';
  variant?: 'tooltip' | 'card' | 'modal';
  showTitle?: boolean;
}

const riskData = {
  PT: {
    title: 'Principal Token (PT)',
    icon: Shield,
    color: 'blue',
    riskLevel: 'Low',
    summary: 'Fixed yield, capital preservation',
    description: 'PT represents the principal portion of a yield-bearing asset. You receive a fixed yield and get back $1 (in underlying) at maturity.',
    pros: [
      'Predictable, fixed returns',
      'Lower risk than YT',
      'Guaranteed value at maturity',
      'Good for capital preservation',
    ],
    cons: [
      'Capped upside (no extra yield if rates increase)',
      'Opportunity cost if yields spike',
      'Locked until maturity for best returns',
    ],
    bestFor: 'Conservative investors who want predictable returns and capital preservation.',
    example: 'Buy PT-sUSDe at $0.98 → Get $1.00 at maturity = 2% fixed gain',
  },
  YT: {
    title: 'Yield Token (YT)',
    icon: Zap,
    color: 'purple',
    riskLevel: 'Medium-High',
    summary: 'Variable yield, higher potential returns',
    description: 'YT captures all the yield generated by the underlying asset until maturity. Your returns depend on actual yield rates.',
    pros: [
      'Higher potential returns if yields stay high',
      'Leveraged exposure to yield',
      'No principal at risk (YT cost is your max loss)',
      'Good for yield farming strategies',
    ],
    cons: [
      'Variable returns - can be zero if yields drop',
      'Worth $0 at maturity (all value is from collected yield)',
      'More complex to understand',
      'Higher volatility',
    ],
    bestFor: 'Aggressive investors who believe yields will remain high or increase.',
    example: 'Buy YT-sUSDe at $0.02 → Collect 10% yield over 90 days = ~2.5% return on YT cost',
  },
  SPLIT: {
    title: 'Balanced Strategy (PT + YT)',
    icon: TrendingUp,
    color: 'green',
    riskLevel: 'Medium',
    summary: 'Balanced risk/reward profile',
    description: 'Splitting between PT and YT gives you both fixed returns and yield exposure. Adjust the ratio based on your risk tolerance.',
    pros: [
      'Diversified exposure',
      'Partial capital protection',
      'Captures some yield upside',
      'Flexible risk management',
    ],
    cons: [
      'Lower max returns than pure YT',
      'Lower capital protection than pure PT',
      'More complex to manage',
    ],
    bestFor: 'Balanced investors who want both security and growth potential.',
    example: '80% PT + 20% YT = Mostly protected capital with some yield upside',
  },
};

const RiskTooltipContent = memo(function RiskTooltipContent({ type }: { type: 'PT' | 'YT' | 'SPLIT' }) {
  const data = riskData[type];
  const Icon = data.icon;

  return (
    <div className="max-w-xs p-1">
      <div className="flex items-center gap-2 mb-2">
        <Icon className={`w-4 h-4 text-${data.color}-500`} />
        <span className="font-semibold text-sm">{data.title}</span>
        <span className={`text-xs px-1.5 py-0.5 rounded bg-${data.color}-100 dark:bg-${data.color}-900/30 text-${data.color}-700 dark:text-${data.color}-300`}>
          {data.riskLevel} Risk
        </span>
      </div>
      <p className="text-xs text-gray-600 dark:text-gray-400 mb-2">{data.summary}</p>
      <p className="text-xs text-gray-500 dark:text-gray-500 italic">{data.bestFor}</p>
    </div>
  );
});

export const RiskExplainerTooltip = memo(function RiskExplainerTooltip({
  type,
  children
}: {
  type: 'PT' | 'YT' | 'SPLIT';
  children: React.ReactNode;
}) {
  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          {children}
        </TooltipTrigger>
        <TooltipContent side="top" className="p-0">
          <RiskTooltipContent type={type} />
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
});

export const RiskExplainerCard = memo(function RiskExplainerCard({ type }: { type: 'PT' | 'YT' | 'SPLIT' }) {
  const data = riskData[type];
  const Icon = data.icon;

  const colorClasses = {
    blue: {
      bg: 'bg-blue-50 dark:bg-blue-900/20',
      border: 'border-blue-200 dark:border-blue-800',
      icon: 'text-blue-600 dark:text-blue-400',
      badge: 'bg-blue-100 dark:bg-blue-900/50 text-blue-700 dark:text-blue-300',
    },
    purple: {
      bg: 'bg-purple-50 dark:bg-purple-900/20',
      border: 'border-purple-200 dark:border-purple-800',
      icon: 'text-purple-600 dark:text-purple-400',
      badge: 'bg-purple-100 dark:bg-purple-900/50 text-purple-700 dark:text-purple-300',
    },
    green: {
      bg: 'bg-green-50 dark:bg-green-900/20',
      border: 'border-green-200 dark:border-green-800',
      icon: 'text-green-600 dark:text-green-400',
      badge: 'bg-green-100 dark:bg-green-900/50 text-green-700 dark:text-green-300',
    },
  };

  const colors = colorClasses[data.color as keyof typeof colorClasses];

  return (
    <div className={`p-4 rounded-xl border ${colors.bg} ${colors.border}`}>
      <div className="flex items-center gap-3 mb-3">
        <div className={`p-2 rounded-lg ${colors.bg}`}>
          <Icon className={`w-5 h-5 ${colors.icon}`} />
        </div>
        <div>
          <h4 className="font-semibold text-gray-900 dark:text-white">{data.title}</h4>
          <span className={`text-xs px-2 py-0.5 rounded-full ${colors.badge}`}>
            {data.riskLevel} Risk
          </span>
        </div>
      </div>

      <p className="text-sm text-gray-600 dark:text-gray-400 mb-3">{data.description}</p>

      <div className="grid grid-cols-2 gap-3 mb-3">
        <div>
          <p className="text-xs font-semibold text-green-700 dark:text-green-400 mb-1">Pros</p>
          <ul className="text-xs text-gray-600 dark:text-gray-400 space-y-1">
            {data.pros.slice(0, 2).map((pro, i) => (
              <li key={i} className="flex items-start gap-1">
                <span className="text-green-500 mt-0.5">+</span>
                {pro}
              </li>
            ))}
          </ul>
        </div>
        <div>
          <p className="text-xs font-semibold text-red-700 dark:text-red-400 mb-1">Cons</p>
          <ul className="text-xs text-gray-600 dark:text-gray-400 space-y-1">
            {data.cons.slice(0, 2).map((con, i) => (
              <li key={i} className="flex items-start gap-1">
                <span className="text-red-500 mt-0.5">-</span>
                {con}
              </li>
            ))}
          </ul>
        </div>
      </div>

      <div className="pt-3 border-t border-gray-200 dark:border-gray-700">
        <p className="text-xs text-gray-500 dark:text-gray-400">
          <span className="font-semibold">Example:</span> {data.example}
        </p>
      </div>
    </div>
  );
});

export const RiskExplainerModal = memo(function RiskExplainerModal({
  isOpen,
  onClose,
  initialType = 'PT',
}: {
  isOpen: boolean;
  onClose: () => void;
  initialType?: 'PT' | 'YT' | 'SPLIT';
}) {
  const [activeType, setActiveType] = useState<'PT' | 'YT' | 'SPLIT'>(initialType);
  const data = riskData[activeType];
  const Icon = data.icon;

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
      <div className="bg-white dark:bg-gray-800 rounded-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto shadow-2xl">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-gray-200 dark:border-gray-700">
          <div className="flex items-center gap-3">
            <HelpCircle className="w-6 h-6 text-blue-600 dark:text-blue-400" />
            <h2 className="text-xl font-bold text-gray-900 dark:text-white">
              Understanding PT & YT
            </h2>
          </div>
          <button
            onClick={onClose}
            className="p-2 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition-colors"
          >
            <X className="w-5 h-5 text-gray-500" />
          </button>
        </div>

        {/* Tabs */}
        <div className="flex border-b border-gray-200 dark:border-gray-700">
          {(['PT', 'YT', 'SPLIT'] as const).map((type) => {
            const typeData = riskData[type];
            const TypeIcon = typeData.icon;
            return (
              <button
                key={type}
                onClick={() => setActiveType(type)}
                className={`flex-1 py-4 px-6 text-sm font-medium transition-colors flex items-center justify-center gap-2 ${
                  activeType === type
                    ? 'border-b-2 border-blue-600 text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-900/20'
                    : 'text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300'
                }`}
              >
                <TypeIcon className="w-4 h-4" />
                {type === 'SPLIT' ? 'Balanced' : type}
              </button>
            );
          })}
        </div>

        {/* Content */}
        <div className="p-6">
          <div className="flex items-center gap-4 mb-6">
            <div className={`p-3 rounded-xl bg-${data.color}-100 dark:bg-${data.color}-900/30`}>
              <Icon className={`w-8 h-8 text-${data.color}-600 dark:text-${data.color}-400`} />
            </div>
            <div>
              <h3 className="text-lg font-bold text-gray-900 dark:text-white">{data.title}</h3>
              <p className="text-sm text-gray-600 dark:text-gray-400">{data.summary}</p>
            </div>
            <span className={`ml-auto px-3 py-1 rounded-full text-sm font-medium bg-${data.color}-100 dark:bg-${data.color}-900/50 text-${data.color}-700 dark:text-${data.color}-300`}>
              {data.riskLevel} Risk
            </span>
          </div>

          <p className="text-gray-600 dark:text-gray-400 mb-6">{data.description}</p>

          <div className="grid md:grid-cols-2 gap-6 mb-6">
            <div className="p-4 bg-green-50 dark:bg-green-900/20 rounded-xl border border-green-200 dark:border-green-800">
              <h4 className="font-semibold text-green-800 dark:text-green-300 mb-3 flex items-center gap-2">
                <span className="text-lg">✓</span> Advantages
              </h4>
              <ul className="space-y-2">
                {data.pros.map((pro, i) => (
                  <li key={i} className="text-sm text-green-700 dark:text-green-400 flex items-start gap-2">
                    <span className="text-green-500 mt-1">•</span>
                    {pro}
                  </li>
                ))}
              </ul>
            </div>

            <div className="p-4 bg-red-50 dark:bg-red-900/20 rounded-xl border border-red-200 dark:border-red-800">
              <h4 className="font-semibold text-red-800 dark:text-red-300 mb-3 flex items-center gap-2">
                <AlertTriangle className="w-4 h-4" /> Considerations
              </h4>
              <ul className="space-y-2">
                {data.cons.map((con, i) => (
                  <li key={i} className="text-sm text-red-700 dark:text-red-400 flex items-start gap-2">
                    <span className="text-red-500 mt-1">•</span>
                    {con}
                  </li>
                ))}
              </ul>
            </div>
          </div>

          <div className="p-4 bg-gray-50 dark:bg-gray-900/50 rounded-xl">
            <h4 className="font-semibold text-gray-900 dark:text-white mb-2">Best For</h4>
            <p className="text-sm text-gray-600 dark:text-gray-400 mb-3">{data.bestFor}</p>
            <div className="p-3 bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700">
              <p className="text-xs text-gray-500 dark:text-gray-400">
                <span className="font-semibold text-gray-700 dark:text-gray-300">Example: </span>
                {data.example}
              </p>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="p-6 border-t border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900/50">
          <button
            onClick={onClose}
            className="w-full py-3 bg-blue-600 hover:bg-blue-700 text-white rounded-xl font-medium transition-colors"
          >
            Got it!
          </button>
        </div>
      </div>
    </div>
  );
});

export const RiskExplainerBadge = memo(function RiskExplainerBadge({
  type,
  showLabel = true,
}: {
  type: 'PT' | 'YT' | 'SPLIT';
  showLabel?: boolean;
}) {
  const data = riskData[type];
  const Icon = data.icon;

  return (
    <RiskExplainerTooltip type={type}>
      <button className="inline-flex items-center gap-1 px-2 py-1 bg-gray-100 dark:bg-gray-700 hover:bg-gray-200 dark:hover:bg-gray-600 rounded-md transition-colors">
        <Icon className="w-3.5 h-3.5 text-gray-600 dark:text-gray-400" />
        {showLabel && (
          <span className="text-xs font-medium text-gray-700 dark:text-gray-300">{type}</span>
        )}
        <HelpCircle className="w-3 h-3 text-gray-400" />
      </button>
    </RiskExplainerTooltip>
  );
});

export default RiskExplainerCard;
